### ISSUE TITLE
New repository for TUF conformance test suite

### ISSUE THREAD

**Issue by AdamKorcz** [theupdateframework/community#24]
Hello,

@jku, @davidkorczynski and I are working on a conformance test suite for TUF clients. We are continuing the work from https://github.com/jku/tuf-conformance and are extending with more infrastructure support and more tests. The idea is that the test suite defines an interface which currently is a list of command-line flags, and then clients can integrate and test against the conformance tests.

One of the goals of this work is to make the conformance suite easily accessible to client-developers, and we would be glad to do the work in the open under a TUF-hosted development repository. As such, we suggest a new TUF-hosted repository where we can do this work in the open and engage with the community.

For info: @lukpueh @haydentherapper, @bobcallaway,

**Comment by jku** [comment]
:+1: I think theupdateframework is the right org for this. I'm happy to be one of the maintainers

**Comment by jku** [comment]
I tried to look for org admin group to ping but that does not actually exist. CCing @JustinCappos at least.

I think `theupdateframework/tuf-conformance` would work as a project name

**Comment by JustinCappos** [comment]
Yes, this all sounds great.  Happy to support this.  @Jussi Kukkonen
***@***.***> , let me know if you need anything from me.

**Comment by joshuagl** [comment]
This is great, thanks. Should we migrate the existing jku/tuf-conformance project to theupdateframework organisation? I can help with that.

**Comment by AdamKorcz** [comment]
> This is great, thanks. Should we migrate the existing jku/tuf-conformance project to theupdateframework organisation? I can help with that.

SGTM

**Comment by jku** [comment]
@joshuagl oh if you have the permissions needed, that  would be great:
* adam has done some work on his fork already but starting with jku/tuf-conformance should work fine
* I suggest we give Adam and David at least commit/merge permissions ("write" in GH?)
* same for me please (although I can take "maintain" as well so we can modify settings)
