### ISSUE TITLE
List maintainers for this repository

### ISSUE THREAD

**Issue by mnm678** [theupdateframework/community#5]
We should add a `MAINTAINERS.md`or similar to make it clear who maintains this repository. If this list is the same as TAP editors (or some other group) we can just include a link to the list in another location.

**Comment by lukpueh** [comment]
Yes, and this repo would also be a perfect fit to make it clear who actually maintains the overall TUF GitHub organisation. And yes, currently, this is probably the group of TAP editors.

FWIW, in our original [community repo draft](https://github.com/lukpueh/tuf-community-repos/tree/main/theupdateframework/community), we envisioned a [`PEOPLE.md`](https://github.com/lukpueh/tuf-community-repos/blob/main/theupdateframework/community/PEOPLE.md) file, which would list the members of the TUF steering committee (i.e. CB, TAP editors, subproject representatives), as defined in a new [`GOVERNANCE.md`](https://github.com/lukpueh/tuf-community-repos/blob/main/theupdateframework/community/GOVERNANCE.md) document. At the time there wasn't enough appetite for this proposal. Maybe this has changed, given the growing community.

**Comment by JustinCappos** [comment]
Yes, let's do this.  

@mnm678 would you submit a PR?  I can approve and merge.

**Comment by h4l0gen** [comment]
Hi @mnm678 @JustinCappos can we close this issue, as completed by [PR ](https://github.com/theupdateframework/community/pull/11)
