### ISSUE TITLE
Add list of adoptions

### ISSUE THREAD

**Issue by mnm678** [theupdateframework/community#6]
We can have a list of companies/organizations that have adopted TUF to allow interested parties to see who else has adopted the project.

**Comment by lukpueh** [comment]
> Is there an advantage over maintaining this in https://theupdateframework.io/adoptions/?

Hm. It probably does lower the barrier for outside collaborators to add a new adoption via PR. 

Either way maybe we could add a `CONTRIBUTING.md` file[^1], which explains how to inform the community about a new adoption.  

[^1]: See existing ideas for [`CONTRIBUTING.md`](https://github.com/lukpueh/tuf-community-repos/blob/main/theupdateframework/community/CONTRIBUTING.md) in our original community repo draft. :P

**Comment by h4l0gen** [comment]
Hi @lukpueh what are your suggestions, should we add `CONTRIBUTING.md` in `Community` repo? And [this ](https://github.com/lukpueh/tuf-community-repos/blob/main/theupdateframework/community/CONTRIBUTING.md)content as you suggested looks good to add. If you like, I want to work on this.

**Comment by mnm678** [comment]
Feel free to open a pr. You can start with the content from the draft repo, and possibly add a description of how adoptions can add themselves to https://theupdateframework.io/adoptions/

**Comment by h4l0gen** [comment]
Sure, I will raise PR, asap!

**Comment by h4l0gen** [comment]
@mnm678 can we close this now.

**Comment by lukpueh** [comment]
Fixed in https://github.com/theupdateframework/community/pull/18/files, which adds instructions to this repo, about how to document a new adoption on theupdateframework.io
